server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    #  History mode (équivalent IIS rewrite)
    location / {
        try_files $uri $uri/ /index.html;
    }

    #  Gestion des 404 comme IIS
    error_page 404 /index.html;

    location = /index.html {
        internal;
    }

    # ⚡ Cache des assets
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        log_not_found off;
    }

    # (optionnel) gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}